# Generated by Django 3.0.6 on 2020-07-08 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200206_0028'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tag',
            new_name='Category',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='tags',
            new_name='categories',
        ),
    ]
